### ISSUE TITLE
CLI commands for events import

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov-cloud#133]
https://github.com/OneGov/onegov-cloud/blob/9ffb45cc1037181c693ff0b230913b3fabc0c8e0/src/onegov/event/cli.py#L300

is command still correct or has it changed to 'event --select ...'

**Comment by DadaDaMotha** [comment]
When running locally, the command is correct as documented. The entry-points are defined in https://github.com/OneGov/onegov-cloud/blob/544bf842e119c6030d33536cba4a79926f9dbf5f/setup.py#L214
However, in the the context of containers like we use them, there is a wrapper to execute the commands inside of the container. The command becomes `sudo ogc event --select ...`.
