### ISSUE TITLE
Banner Corona Anlässe

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov-cloud#134]
Zur Eindämmung des Coronavirus verbietet der Bundesrat öffentliche Veranstaltungen. Alle Veranstaltungen sind damit abgesagt und finden nicht statt.

**Comment by freinhard** [comment]
https://github.com/OneGov/onegov-cloud/search?q=corona_message

**Comment by freinhard** [comment]
https://github.com/OneGov/onegov-cloud/blob/b9fc08c98402486f783287892e70b6a14776f251/src/onegov/org/templates/layout.pt

**Comment by freinhard** [comment]
https://github.com/OneGov/onegov-cloud/blob/master/src/onegov/org/templates/layout.pt#L157 -> https://github.com/OneGov/onegov-cloud/commit/a34a36c8da1e04c9338bf0e5510f4e5586ccb0b5#diff-1767f60c2c5720e7cdb1012f6e48a2a9168f89a58cc4964ee0ef1c61347ffb70

**Comment by treinhard** [comment]
Enabled with 52902885

**Comment by freinhard** [comment]
https://github.com/OneGov/onegov-cloud/commit/5560b2aa5c7f2b4b5d23de0259c981f4572e2fa6#diff-1767f60c2c5720e7cdb1012f6e48a2a9168f89a58cc4964ee0ef1c61347ffb70

**Comment by freinhard** [comment]
Dans le but de contenir le coronavirus, le Conseil fédéral interdit les manifestations publiques. Tous les événements sont donc annulés et n'auront pas lieu.
