### ISSUE TITLE
Speed-up election-day test suite

### ISSUE THREAD

**Issue by href** [OneGov/onegov-cloud#5]
The election-day tests are the slowest set of tests we have. At least part of the reason is the fact that a lot of time is spent on setting up fixtures for the view tests. Those fixtures are set up by calling view methods, which is a lot slower than if the fixtures were simply added using SQLAlchemy queries.

See https://github.com/OneGov/onegov-cloud/blob/master/tests/onegov/election_day/common.py

When running just the view tests, of 2:30 minutes, a 30 seconds are just spent inside these functions.

**Comment by DadaDaMotha** [comment]
In  in **branch upload_majorz_as_csv**, I created a fixture to replace `upload_majorz_election` (webtest) that reads the csv directly to add it to the database. However, this approach with Webtest does not seem to work if the data is not uploaded by webtest itself.
Here is the test:
`py.test tests/onegov/election_day/ -k test_view_election_lists_panachage_proporz`

**Comment by href** [comment]
The problem is that webtest uses a new transaction (any request to the application does really), and since you have not committed your changes that you made during when creating your fixture, you do not see those changes.

I got a step further wrapping `_majorz_election` with `transaction.begin()` and `transaction.commit()`. But then another error follows, since the return values are bound to the session which expires during the transaction commit.

There you might have to change a few things to maybe not return a session-bound object (for example, if you just return a string id, it is not bound to the session). Or you use [SQLAlchemy's session merging](https://docs.sqlalchemy.org/en/13/orm/session_state_management.html#merging).
